### ISSUE TITLE
修复FormView的waitConfirm接口

### ISSUE THREAD

**Issue by otakustay** [ecomfe/ub-ria#184]
@curarchy 好像是你引入的……

在某次提交中，`FormView#waitConfirm`接口被修改了签名，且内部逻辑完全只为提交或取消时的提示服务，甚至直接使用了`Warn`控件

我在Code Review的时候疏忽了，并没有仔细地看各方法的签名和实现

简单来说，这种行为是非常危险的，我们所谓的`override`，至少要有以下前提：

1. 签名是相同的
2. 签名不相同的情况下兼容父类的签名
3. 可以应付父类同方法设计所面向的场景

而这一次的修改违反了这些前提，严格来说这并不是`override`，而是一种胡乱的“重新定义”。这会致使`FormView`的某些子类需要真正的`waitConfirm`的功能时，出现不可预期的结果

我建议恢复原来的`waitConfirm`，同时将现在的这个改为`waitConfirmForType`之类的方法

还请在我们beta版前搞定，同时看一下哪里有相关的调用确保没有问题

**Comment by curarchy** [comment]
我查看一下。

**Comment by curarchy** [comment]
我看了下那个提交。https://github.com/ecomfe/ub-ria/pull/155/files

最先的版本是只有 `FormView#waitCancelConfirm`这个接口，没有`FormView#waitConfirm`这个接口。原先所有逻辑都在`FormView#waitCancelConfirm`里。

为了满足提交前确认这个需求，我做了以下处理：

1. 保留`FormView#waitCancelConfirm`，并未修改签名。其中的大部分逻辑放入了新接口`FormView#waitConfirm`中。然后`waitCancelConfirm`去调用`waitConfirm`，这样原先的取消前确认功能得以保留。

2. 新增一个`FormView#`waitSubmitConfirm`。默认返回`Deferred.resolved()`，这样不影响原本新建的逻辑。如果新增前需要确认，重写该方法调用`FormView#waitConfirm`即可。

3. 新增了一个`FormView#waitConfirm`接口，提供弹警告条功能。供取消提交调用。如果提交也需要的话，可以重写`FormView#`waitSubmitConfirm`调用。该接口比1、2两个接口多了个参数`type`，用以调整文案。

**Comment by otakustay** [comment]
问题在于，waitConfirm这个接口是BaseView已经有的，相当于你把基类有的接口给破坏了……大概是不知道基类正好也有这方法吧？



Best regards

Gray Zhang



在 2015年2月2日 下午2:26:08, Curarchy (notifications@github.com) 写到:

我看了下那个提交。https://github.com/ecomfe/ub-ria/pull/155/files

最先的版本是只有 FormView#waitCancelConfirm这个接口，没有FormView#waitConfirm这个接口。原先所有逻辑都在FormView#waitCancelConfirm里。

为了满足提交前确认这个需求，我做了以下处理：

保留FormView#waitCancelConfirm，并未修改签名。其中的大部分逻辑放入了新接口FormView#waitConfirm中。然后waitCancelConfirm去调用waitConfirm，这样原先的取消前确认功能得以保留。

新增一个FormView#waitSubmitConfirm。默认返回Deferred.resolved()，这样不影响原本新建的逻辑。如果新增前需要确认，重写该方法调用FormView#waitConfirm`即可。

新增了一个FormView#waitConfirm接口，提供弹警告条功能。供取消提交调用。如果提交也需要的话，可以重写FormView#waitSubmitConfirm调用。该接口比1、2两个接口多了个参数type`，用以调整文案。

**Comment by curarchy** [comment]
额。。。明白了。。。随意起了个名字出问题了。

**Comment by curarchy** [comment]
fixed
https://github.com/ecomfe/ub-ria/pull/186
