### ISSUE TITLE
修改waitConfirm接口

### ISSUE THREAD

**Issue by otakustay** [ecomfe/ub-ria#185]
## 情况

在最初的设计中，`waitConfirm`返回一个`Promise`，用户确认的时候进行`resolve()`，取消的时候进行`reject()`，当时的设计意图也很明确，用户确认和用户拒绝正好对应2个状态。

但事实上，这个设计恰恰是错误的。根据最新的标准Promise的实现，`reject()`状态对应的处理方法是`catch()`，这很明确地表示了`reject`其实是一种“异常”的状态，而非正常的分支。

同时官方文档也已经明确说了这点：http://www.w3.org/2001/tag/doc/promises-guide#rejections-should-be-exceptional

> Bad uses of rejections include:
>
> When the operation is phrased as a question, and the answer is negative: for example if the operation is hasPermissionToAccessUsersContacts() and the user has denied permission, then it should return a promise fulfilled with false; it should not reject.

如果继续按最初设计的使用，当Promise全局错误的功能实现后，用户选择“取消”会触发`window.onerror`，对我们的错误收集造成影响

## 解决方案

现存有2个解决方案：

### 完整修改

修改`waitConfirm`，使之在用户2种选择下均进行`resolve`，且提供一个`boolean`值作为结果

这个方法需要修改不少的使用了`waitConfirm`的代码，相对麻烦一些

### 向后兼容方案

考虑到我们大部分`waitConfirm`只需要用户确认的场景下的处理，按以下方式修改：

1. 添加`waitDecision`方法，用户作任何选择均`resolve`，且提供一个字符串`"ok"`或`"cancel"`作为值
2. `waitConfirm`调用`waitDecision`，且只在`"ok"`的情况下`resolve`，这会导致用户取消时，返回的Promise永远也不会有结果

`waitDecision`方法在后续如果有进一步的场景可以扩展为用户从任意N个选择中决定1个，通过字符串来表示用户的选择，因此具有扩展性

这个方案唯一的问题在于“一个永远不会有结果的Promise”是否会有隐患，我和mozilla的人们讨论下再决定

## 总结

这个问题影响面很广，给我的影响也同样深刻，总结一下：

1. 概念正确很重要。用任何东西，首先要符合其使用的场景和概念，如果因为“这东西正好这场景下用起来方便”而去用了，就是非常作死的行为，而且真的会死
2. 要分清“异常状态”和“不期望的分支”这两种情况。比如去跟美女告白被拒绝了，是“不期望的分支”，但一个路人看你告白不爽拿刀捅了你，这就是“异常状态”了
3. 接口的设计要慎之又慎，宁可丑一点也不会错一步。如果无法知道自己的设计是否正确，则应该保留一个最原始也最易在上面进行二次封装的接口

**Comment by otakustay** [comment]
@Justineo 我看你们那边也是这样的……

**Comment by Justineo** [comment]
从你们那版本 fork 出来的……

**Comment by otakustay** [comment]
看得出来，这就叫一人跑错全员掉坑……所以要不一起改，或者你们想保持不动？



Best regards

Gray Zhang



在 2015年2月2日 下午1:47:53, Yiling GU (notifications@github.com) 写到:

从你们那版本 fork 出来的……

**Comment by Justineo** [comment]
我看代码很多都是只处理了 resolved 时的后续逻辑，这种情况下这个改动是透明的吧……

**Comment by otakustay** [comment]
嗯，是透明的，我就担心“永远不会有结果的Promise”会不会有啥问题



Best regards

Gray Zhang



在 2015年2月2日 下午2:04:41, Yiling GU (notifications@github.com) 写到:

我看代码很多都是只处理了 resolved 时的后续逻辑，这种情况下这个改动是透明的吧……

**Comment by Justineo** [comment]
不就相当于挂了一个 callback 但是永远不调用么

**Comment by otakustay** [comment]
es-discuss的同志们也纷纷表示这么干没啥问题，顶多有内存泄露，就像所有的事件都可能存在的问题

所以就这么干好了呗？



Best regards

Gray Zhang



在 2015年2月2日 下午2:32:13, Yiling GU (notifications@github.com) 写到:

不就相当于挂了一个 callback 但是永远不调用么
