### ISSUE TITLE
[FormView#getEntity]增加对嵌套属性名称的解构

### ISSUE THREAD

**Issue by Exodia** [ecomfe/ub-ria#219]
实际场景：

```html
<input data-ui-name="basic.flowTpye" value="1213">
```

目前 getEntity 返回的是： {"basic.flowType":1213}.

期望能够解析成为： {basic: {flowType: 1213}}

**Comment by otakustay** [comment]
请Review

**Comment by otakustay** [comment]
还剩个问题，对于不使用JSON为请求格式的系统不能这么搞，不然序列化为`form-encoded`会出问题

我会在`FormView`上增加一个属性控制这个功能的开启/关闭
