### ISSUE TITLE
ListView.js getSearchArgs

### ISSUE THREAD

**Issue by homfen** [ecomfe/ub-ria#258]
```
var args = form ? form.getData() : {};
```
改为：
```
var args = (form && !form.isHidden()) ? form.getData() : {};
```
filter是hidden的情况下不需要getData

**Comment by bobshen** [comment]
从语义上，hidden 不等于 disabled。

**Comment by bobshen** [comment]
从效果上，hidden不等于disabled。

隐藏的控件仍然是可以获取到的，或许应该是判断是否 form 的状态是 isDisabled。

或者说，disabled的form，getData 的结果本应该就是空。

**Comment by otakustay** [comment]
现的实现似乎会在这个Form隐藏的时候自动把所有的查询控件恢复到默认值，因此缺少`isHidden()`的判断并不影响逻辑

另外即便`Form`是隐藏的，我们还是需要这些控件的值，因为我们需要一个默认值，而不是没有值

还请提供一下什么样的场景会需要这个额外的`isHidden()`的检测才可以保证逻辑的正确性？

**Comment by homfen** [comment]
filter里面包含calendar控件的时候，会有个默认值，就是当前日期
翻页的时候会把这个值出来

**Comment by otakustay** [comment]
这个有点类似status默认值是all的感觉，用defaultArgs配置一下（对于日历应该是new Date()？）会自动去掉的



Best regards

Gray Zhang



在 2016年1月21日 下午3:16:08, Homfen (notifications@github.com) 写到:

filter里面包含calendar控件的时候，会有个默认值，就是当前日期
翻页的时候会把这个值出来

**Comment by homfen** [comment]
其实不是calendar，是range-calendar，有begin和end两个日期，放在defaulgArgs里面不好处理
而且defaultArgs里面的new Date()和calendar的new Date()是不一样的，时分秒

**Comment by otakustay** [comment]
理解你的场景，但是添加隐藏时不读取值会影响现有的一些场景的，因为我们确实要一个默认值来走后续的逻辑

因此你的情况，我是否可以建议自行进行一些处理



Best regards

Gray Zhang



在 2016年1月21日 下午3:45:41, Homfen (notifications@github.com) 写到:

其实不是calendar，是range-calendar，有begin和end两个日期，放在defaulgArgs里面不好处理
而且defaultArgs里面的new Date()和calendar的new Date()是不一样的，时分秒

**Comment by homfen** [comment]
恩，那我自己处理下吧
