### ISSUE TITLE
有关defaultArgs的设计问题

### ISSUE THREAD

**Issue by otakustay** [ecomfe/ub-ria#260]
`ListModel`有一个`defaultArgs`属性，用于指定列表查询的默认参数，它有以下特点：

1. 是一个`Object`类型
2. 这个对象的数据会被追加到`Model`实例中，即对象是`{status: 0}`则`this.get('status') === 0`

在面向ES5的版本中，这个设计是这样的：

```js
exports.constructor = function () {
    this.$super(arguments);

    // 追加到实例上
    u.each(
        this.getDefaultArgs(),
        function (value, key) {
            if (!this.has(key)) {
                this.set(key, value);
            }
        },
        this
    );
}
```

所以在子类中我们只要这样写就可以了：

```js
exports.defaultArgs = {
    ...
};
```

但是到了ES6时代，我们遇到2种情况，一个属性可以表达为[Class Properties](https://github.com/jeffmo/es-class-fields-and-static-properties)，有些则使用getter：

```js
class MyListModel extends ListModel {
    defaultArgs = {
        ...
    }
}

class MyListModel extends ListModel {
    get defaultArgs() {
        return {
            ...
        }
    }
}
```

不幸的是，支持这2种方式的实现是不同的

如果使用Class Properties，则无法在构造函数中去做追加数据的操作，因为在ES6的模型下，调用顺序是：

1. 基类Class Propertie赋值
2. 基类的构造函数
3. 子类Class Properties赋值
4. 子类的构造函数

而数据追加发生在上面的第2步，无法获取子类定义的`defaultArgs`

在这种方式下，我们需要通过`set defaultArgs`来定义这段逻辑：

```js
class ListModel {
    set defaultArgs(value) {
        this[DEFAULT_ARGS] = value;

        // 把默认参数补上，不然像表格的`orderBy`字段没值表格就不能正确显示
        u.each(
            this.defaultArgs,
            (value, key) => {
                if (!this.has(key)) {
                    this.set(key, value);
                }
            }
        );
    }
}
```

而如果开发者使用`get defaultArgs`而不是Class Properties定义，那么整个流程并不会触发`set defaultArgs`的逻辑，也就没有办法做数据的追加

现在来看，以**在构造函数结束后数据就完成追加**为前提，我们只能采用二选一的方案，**两者都做的话不知道会发生什么，感觉不安全**

所以我们现在有4种解决办法：

1. 在构造函数中追加数据，只允许使用`get defaultArgs`
2. 在`set defaultArgs`中追加数据，只允许使用Class Properties声明`defaultArgs`
3. 同时做1和2，但使用Class Properties时会执行2次数据追加操作，不确定有什么副作用（比如`defaultArgs`里有个属性是个getter）
4. 在`load`方法前去追加数据，代价是构造函数至`load`调用这期间是无法在实例上获得这些数据的（当前并未发现有在这个阶段获取数据的代码）

请参考及讨论我们的解决方案

**Comment by Exodia** [comment]
我倾向1，类似的还有 uiEvents，uiProperties 这些原型链的对象配置，在子类要 merge 基类配置的时候总是很麻烦，本身 defaultArgs 也不应该会去依赖生命周期，而1的好处也在于此。

**Comment by leeight** [comment]
我们现在大部分采用`1`的方案：`在构造函数中追加数据，只允许使用get defaultArgs`
