### ISSUE TITLE
ListAction的查询过程可能丢失部分参数

### ISSUE THREAD

**Issue by bobshen** [ecomfe/ub-ria#266]
Version: `ub-ria 4.0`

进入列表后，我们现在允许通过 `修改筛选条件`、`修改关键词`、`修改pager参数`、`修改列表排序条件` 等操作修改列表的查询结果。

现在基类的实现主要是通过 `reloadWithQueryUpdate` 的方式刷新页面URL完成的。但是现在基类的实现可能会导致丢失某些URL上的参数。

大部分情况下，URL上的参数是各个查询组件的参数的合集，但也可能有些参数不属于查询意图，而用于其他用途。在这种场景下，修改查询参数后进行重新reload后却不能保持这些参数。

从功能定义上，`performSearch` 和 `getSearchQuery` 都不适合做这些事。因为列表的查询并非总是刷新的，也有可能前端静态静态数据源切换啥的。

所以看起来会引起URL变化的 `reloadWithQueryUpdate` 方法是最适合升级来满足需求的。
比如在 `redirect` 之前将当前URL上的完整query，作为类似 `model.defaultArgs` 的默认查询参数，与新的请求参数进行merge。

**Comment by otakustay** [comment]
假设通过`getSearchQuery`拿到的参数和URL比较少了`foo`，基类恐怕没办法知道是因为foo这个查询条件的控件没有值（没有foo正常），还是因为foo是个查询无关的参数（要把foo加回去）

所以基类可能无能为力

**Comment by otakustay** [comment]
考虑下在purify前就和url参数做比对也许行，关键是：是否在url里且不在控件提供的值里的东西，一定都是要保留的

**Comment by bobshen** [comment]
> 因为foo这个查询条件的控件没有值（没有foo正常），还是因为foo是个查询无关的参数

如果不存在 `foo` 这个查询控件，那么进入 `reloadWithQueryUpdate` 时，`args` 中便没有这个属性，把 URL中的 `foo` 补回去很好理解；
如果存在 `foo` 这个查询控件，那么进入 `reloadWithQueryUpdate`  时，`args` 有 `foo` 这个属性，但是value是''，那么这个作为优先级比较高的参数，覆盖 URL 和 defaultArgs 中的同名属性也是可以的

**Comment by otakustay** [comment]
所以用purify(merge(url.query, searchArgs))这个逻辑对吧，如果靠谱的话可以考虑这么来

Shen Bin <notifications@github.com>于2016年7月11日 周一下午9:21写道：

**Comment by bobshen** [comment]
> 所以用purify(merge(url.query, searchArgs))这个逻辑对吧，如果靠谱的话可以考虑这么来

是的，`u.purify(args, {...defaultArgs, ...this.context.url.getQuery()})` 我想的是改成这样。

> 关键是：是否在url里且不在控件提供的值里的东西，一定都是要保留的

关于这点，其实我也在思考。或者问题可以改为：什么情况下出现在url中且不在查询参数中的参数，在页面reload时不应该保留？

**Comment by otakustay** [comment]
你这个逻辑完全没保留url中的参数吧。。。purify的第二个参数是参考值，不会加到结果里去的

看PR吧

**Comment by bobshen** [comment]
嗯，之前示例的是有问题... 没想到 purify 的defaults 参数，不是类似 u.defaults 的作用。

**Comment by bobshen** [comment]
那这个issue可以close了
