### ISSUE TITLE
tpl.js支持ie10、9、8跨域加载模板

### ISSUE THREAD

**Issue by yanghuabei** [ecomfe/ub-ria#274]
接入cdn后，`.tpl.html`文件的加载需要跨域，服务端设置好允许跨域头之后，需要tpl.js提供跨域支持。ie10、9、8需要使用XDomainRequest实现。

```
// 跨域时，兼容ie10、9、8
if (isCrossRigion && window.XDomainRequest) {
    var xdr = new window.XDomainRequest();
    xdr.open('GET', url);
    xdr.onload = function () {
        addTemplate(xdr.responseText);
    };
}
// 非跨域或非ie浏览器
else {
}
```

**Comment by otakustay** [comment]
话说我们线上的模板不是打包成一个js文件的么……最关键的是不是text插件要改才是王道

**Comment by yanghuabei** [comment]
额 是的。我搞错了，那些没打包的模板使用text插件加载的....

**Comment by otakustay** [comment]
text的可以用InlineText，要的话找我好了

-- 
Gray Zhang

在 2016年9月23日 at 下午1:58:15, hiby (notifications@github.com) 写到:
